apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: uptime-monitor
  name: db-pvc
spec:
  storageClassName: storage-class
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi