apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: uptime-monitor
  name: storage-class
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete